package habit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMUNITY_RECORD.
 */
public class CommunityRecord {

    private Long id;
    /** Not-null value. */
    private String communityId;
    private String userName;
    private String avatarUrl;

    public CommunityRecord() {
    }

    public CommunityRecord(Long id) {
        this.id = id;
    }

    public CommunityRecord(Long id, String communityId, String userName, String avatarUrl) {
        this.id = id;
        this.communityId = communityId;
        this.userName = userName;
        this.avatarUrl = avatarUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCommunityId() {
        return communityId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommunityId(String communityId) {
        this.communityId = communityId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

}
