package habit.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HABIT_RECORD.
 */
public class HabitRecord {

    private Long id;
    /** Not-null value. */
    private String habitId;
    /** Not-null value. */
    private String habitName;
    private Integer persistCount;
    private String iconUrl;

    public HabitRecord() {
    }

    public HabitRecord(Long id) {
        this.id = id;
    }

    public HabitRecord(Long id, String habitId, String habitName, Integer persistCount, String iconUrl) {
        this.id = id;
        this.habitId = habitId;
        this.habitName = habitName;
        this.persistCount = persistCount;
        this.iconUrl = iconUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getHabitId() {
        return habitId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHabitId(String habitId) {
        this.habitId = habitId;
    }

    /** Not-null value. */
    public String getHabitName() {
        return habitName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHabitName(String habitName) {
        this.habitName = habitName;
    }

    public Integer getPersistCount() {
        return persistCount;
    }

    public void setPersistCount(Integer persistCount) {
        this.persistCount = persistCount;
    }

    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

}
